Description: >
    Oscar Forero / Udacity
    This template deploys a VPC, with a pair of public and private subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets. It deploys a pair of NAT Gateways (one in each AZ), 
    and default routes for them in the private subnets.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
  Backend1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07a29e5e945228fa1
      NetworkInterfaces:
        - DeviceIndex: 0
          DeleteOnTermination: true
          AssociatePublicIpAddress: true
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-PRI1-SN

  Backend2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07a29e5e945228fa1
      NetworkInterfaces:
        - DeviceIndex: 0
          DeleteOnTermination: true
          AssociatePublicIpAddress: true
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-PRI2-SN            

  Webserver1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07a29e5e945228fa1
      NetworkInterfaces:
        - DeviceIndex: 0
          DeleteOnTermination: true
          AssociatePublicIpAddress: true
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-PUB1-SN

  Webserver2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07a29e5e945228fa1
      NetworkInterfaces:
        - DeviceIndex: 0
          DeleteOnTermination: true
          AssociatePublicIpAddress: true
          SubnetId: 
            Fn::ImportValue: !Sub ${EnvironmentName}-PUB2-SN